

#include "spipe/blocks/BuildStructures.h"
#include "spipe/blocks/Clone.h"
#include "spipe/blocks/CutAndPaste.h"
#include "spipe/blocks/FindSymmetryGroup.h"
#include "spipe/blocks/GeomOptimise.h"
#include "spipe/blocks/KeepStableCompositions.h"
#include "spipe/blocks/KeepTopN.h"
#include "spipe/blocks/KeepWithinXPercent.h"
#include "spipe/blocks/LoadStructures.h"
#include "spipe/blocks/NiggliReduce.h"
#include "spipe/blocks/PasteFragment.h"
#include "spipe/blocks/RemoveDuplicates.h"
#include "spipe/blocks/Rescale.h"
#include "spipe/blocks/RunPotentialParamsQueue.h"
#include "spipe/blocks/SearchStoichiometries.h"
#include "spipe/blocks/SeparateAtoms.h"
#include "spipe/blocks/Shrink.h"
#include "spipe/blocks/WriteStructures.h"
